paths:
  /repositories:
    get:
      summary: Get a list of user's repositories
      parameters:
        - name: username
          in: query
          required: true
          type: string
        - name: Accept
          in: header
          required: true
          type: string
      responses:
        200:
          description: Successful retrieval of user's repositories
        404:
          description: User not found
        406:
          description: Unsupported 'Accept' header (including xml format)
          content:
            application/xml:
              example:
                status: 406
                message: XML format not supported
            another format:
              example:
                status: 406
                message: Unsupported 'Accept' header

